<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Pradnyas-MacBook-Air.local" failures="1" tests="1" name="Default test" time="7.839" errors="0" timestamp="2024-10-25T07:39:53 IST">
  <testcase classname="piku_mau.CartCreation" name="cart_already_exists_for_user" time="6.779">
    <failure type="java.lang.IllegalArgumentException" message="Unrecognized field &amp;quot;error&amp;quot; (class models.UserSignupResponse), not marked as ignorable (3 known properties: &amp;quot;data&amp;quot;, &amp;quot;headers&amp;quot;, &amp;quot;statusCode&amp;quot;])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse[&amp;quot;error&amp;quot;])">
      <![CDATA[java.lang.IllegalArgumentException: Unrecognized field "error" (class models.UserSignupResponse), not marked as ignorable (3 known properties: "data", "headers", "statusCode"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse["error"])
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394)
at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4325)
at utilities.ApiResponseDeserializer.deserializeResponse(ApiResponseDeserializer.java:31)
at clients.UserClient.authenticateUser(UserClient.java:82)
at clients.UserClient.CreateCart(UserClient.java:92)
at piku_mau.CartCreation.cart_already_exists_for_user(CartCreation.java:48)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class models.UserSignupResponse), not marked as ignorable (3 known properties: "data", "headers", "statusCode"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4389)
... 31 more
]]>
    </failure>
  </testcase> <!-- cart_already_exists_for_user -->
  <testcase classname="piku_mau.CartCreation" name="create_new_cart_for_user" time="0.0">
    <ignored/>
  </testcase> <!-- create_new_cart_for_user -->
</testsuite> <!-- Default test -->
