<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="1" passed="0" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2024-10-18T19:05:20 IST" name="Default suite" finished-at="2024-10-18T19:05:26 IST" duration-ms="5302">
    <groups>
    </groups>
    <test started-at="2024-10-18T19:05:20 IST" name="Default test" finished-at="2024-10-18T19:05:26 IST" duration-ms="5302">
      <class name="piku.LoginAPI">
        <test-method is-config="true" signature="setBaseURI()[pri:0, instance:piku.LoginAPI@21337f7b]" started-at="2024-10-18T19:05:20 IST" name="setBaseURI" finished-at="2024-10-18T19:05:21 IST" duration-ms="679" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setBaseURI -->
        <test-method signature="verifySuccessfulLoginWithValidCredentials()[pri:0, instance:piku.LoginAPI@21337f7b]" started-at="2024-10-18T19:05:21 IST" name="verifySuccessfulLoginWithValidCredentials" finished-at="2024-10-18T19:05:26 IST" duration-ms="4489" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[User token should be present and have the expected format
Expected: a string matching the pattern '^Bearer [\w-\.]+(.[\w-]+)*$'
     but: was "eyJhbGciOiJIUzI1NiIsImtpZCI6ImV3UjBaUnlOMG5IRHE0RzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25hcW1odmZzZGhpZ2VzdnJyamNsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMDgyNWUxNy04MTgwLTQ2MjgtYWY3OC03YjY0MGIwODc5ZWQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzI5MjYyMTI1LCJpYXQiOjE3MjkyNTg1MjUsImVtYWlsIjoiOWY3NTYzODEtNzQzYy00OWY0LWE4NDMtNmUyMmExZjM5ZDA3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiI5Zjc1NjM4MS03NDNjLTQ5ZjQtYTg0My02ZTIyYTFmMzlkMDdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImQwODI1ZTE3LTgxODAtNDYyOC1hZjc4LTdiNjQwYjA4NzllZCJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzI5MjU4NTI1fV0sInNlc3Npb25faWQiOiI4NDNkYTdlZS1jOWQ1LTQzY2EtODE3Yy05ZWRkY2JhMzRhYWUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.Ycu7Q2PcTzuea-n3zEIWlFmaO-JFhdRvOHd5yJZUJmM"]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: User token should be present and have the expected format
Expected: a string matching the pattern '^Bearer [\w-\.]+(.[\w-]+)*$'
     but: was "eyJhbGciOiJIUzI1NiIsImtpZCI6ImV3UjBaUnlOMG5IRHE0RzYiLCJ0eXAiOiJKV1QifQ.eyJpc3MiOiJodHRwczovL25hcW1odmZzZGhpZ2VzdnJyamNsLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiJkMDgyNWUxNy04MTgwLTQ2MjgtYWY3OC03YjY0MGIwODc5ZWQiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzI5MjYyMTI1LCJpYXQiOjE3MjkyNTg1MjUsImVtYWlsIjoiOWY3NTYzODEtNzQzYy00OWY0LWE4NDMtNmUyMmExZjM5ZDA3QGdtYWlsLmNvbSIsInBob25lIjoiIiwiYXBwX21ldGFkYXRhIjp7InByb3ZpZGVyIjoiZW1haWwiLCJwcm92aWRlcnMiOlsiZW1haWwiXX0sInVzZXJfbWV0YWRhdGEiOnsiZW1haWwiOiI5Zjc1NjM4MS03NDNjLTQ5ZjQtYTg0My02ZTIyYTFmMzlkMDdAZ21haWwuY29tIiwiZW1haWxfdmVyaWZpZWQiOmZhbHNlLCJwaG9uZV92ZXJpZmllZCI6ZmFsc2UsInN1YiI6ImQwODI1ZTE3LTgxODAtNDYyOC1hZjc4LTdiNjQwYjA4NzllZCJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzI5MjU4NTI1fV0sInNlc3Npb25faWQiOiI4NDNkYTdlZS1jOWQ1LTQzY2EtODE3Yy05ZWRkY2JhMzRhYWUiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.Ycu7Q2PcTzuea-n3zEIWlFmaO-JFhdRvOHd5yJZUJmM"
at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
at piku.LoginAPI.verifySuccessfulLoginWithValidCredentials(LoginAPI.java:37)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifySuccessfulLoginWithValidCredentials -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:piku.LoginAPI@21337f7b]" started-at="2024-10-18T19:05:26 IST" name="tearDown" finished-at="2024-10-18T19:05:26 IST" duration-ms="6" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- piku.LoginAPI -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
