<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Pradnyas-MacBook-Air.local" failures="0" tests="1" name="piku.LoginAPI" time="3.565" errors="1" timestamp="2024-10-24T10:10:06 IST" skipped="0">
  <testcase classname="piku.LoginAPI" name="verifySuccessfulLoginWithValidCredentials" time="3.565">
    <error message="Unrecognized field &quot;error&quot; (class models.UserSignupResponse), not marked as ignorable (3 known properties: &quot;data&quot;, &quot;headers&quot;, &quot;statusCode&quot;])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse[&quot;error&quot;])" type="java.lang.IllegalArgumentException">
      <![CDATA[java.lang.IllegalArgumentException: Unrecognized field "error" (class models.UserSignupResponse), not marked as ignorable (3 known properties: "data", "headers", "statusCode"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse["error"])
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4394)
at com.fasterxml.jackson.databind.ObjectMapper.convertValue(ObjectMapper.java:4325)
at utilities.ApiResponseDeserializer.deserializeResponse(ApiResponseDeserializer.java:31)
at clients.UserClient.authenticateUser(UserClient.java:81)
at piku.LoginAPI.verifySuccessfulLoginWithValidCredentials(LoginAPI.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:139)
at org.testng.internal.invokers.TestInvoker.invokeMethod(TestInvoker.java:677)
at org.testng.internal.invokers.TestInvoker.invokeTestMethod(TestInvoker.java:221)
at org.testng.internal.invokers.MethodRunner.runInSequence(MethodRunner.java:50)
at org.testng.internal.invokers.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:969)
at org.testng.internal.invokers.TestInvoker.invokeTestMethods(TestInvoker.java:194)
at org.testng.internal.invokers.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:148)
at org.testng.internal.invokers.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1597)
at org.testng.TestRunner.privateRun(TestRunner.java:829)
at org.testng.TestRunner.run(TestRunner.java:602)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:437)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:431)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:391)
at org.testng.SuiteRunner.run(SuiteRunner.java:330)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:95)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1256)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1176)
at org.testng.TestNG.runSuites(TestNG.java:1099)
at org.testng.TestNG.run(TestNG.java:1067)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:293)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:91)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "error" (class models.UserSignupResponse), not marked as ignorable (3 known properties: "data", "headers", "statusCode"])
 at [Source: UNKNOWN; byte offset: #UNKNOWN] (through reference chain: models.UserSignupResponse["error"])
at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:1127)
at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1989)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1700)
at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1678)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:319)
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:176)
at com.fasterxml.jackson.databind.ObjectMapper._convert(ObjectMapper.java:4389)
... 30 more
]]>
    </error>
  </testcase> <!-- verifySuccessfulLoginWithValidCredentials -->
  <system-out/>
</testsuite> <!-- piku.LoginAPI -->
